export const TOKENS = {
  STOCK_BALANCE_REPOSITORY: Symbol('STOCK_BALANCE_REPOSITORY'),
  WAREHOUSE_REPOSITORY: Symbol('WAREHOUSE_REPOSITORY'),
  AUTH_REPOSITORY: Symbol('AUTH_REPOSITORY'),
  LOGIN_USE_CASE: Symbol('LOGIN_USE_CASE'),
  BIOMETRIC_UNLOCK_USE_CASE: Symbol('BIOMETRIC_UNLOCK_USE_CASE'),
  ADJUST_STOCK_USE_CASE: Symbol('ADJUST_STOCK_USE_CASE'),
  RESOLVE_CONFLICT_USE_CASE: Symbol('RESOLVE_CONFLICT_USE_CASE'),
  GET_CONFLICT_DETAIL_USE_CASE: Symbol('GET_CONFLICT_DETAIL_USE_CASE'),
  SYNC_CENTRE_USE_CASE: Symbol('SYNC_CENTRE_USE_CASE'),
  HTTP_CLIENT: Symbol('HTTP_CLIENT'),
  MUTATION_QUEUE: Symbol('MUTATION_QUEUE'),
  SYNC_ENGINE: Symbol('SYNC_ENGINE'),
  LOGGER: Symbol('LOGGER'),
  KEYCHAIN: Symbol('KEYCHAIN'),
  NETWORK: Symbol('NETWORK'),
  DATABASE: Symbol('DATABASE'),
} as const;

export type Token = (typeof TOKENS)[keyof typeof TOKENS];
