export const TOKENS = {
  STOCK_BALANCE_REPOSITORY: Symbol('STOCK_BALANCE_REPOSITORY'),
  WAREHOUSE_REPOSITORY: Symbol('WAREHOUSE_REPOSITORY'),
  AUTH_REPOSITORY: Symbol('AUTH_REPOSITORY'),
  HTTP_CLIENT: Symbol('HTTP_CLIENT'),
  MUTATION_QUEUE: Symbol('MUTATION_QUEUE'),
  SYNC_ENGINE: Symbol('SYNC_ENGINE'),
  LOGGER: Symbol('LOGGER'),
  KEYCHAIN: Symbol('KEYCHAIN'),
  NETWORK: Symbol('NETWORK'),
} as const;

export type Token = (typeof TOKENS)[keyof typeof TOKENS];
